export const logos = {
  iit: [
    // { id: 1, name: "IISc Bangalore", logo: "/IISc_Master_Seal.png" },
    {
      id: 2,
      name: "IIT Kharagpur",
      logo: "/imgi_19_IIT_Kharagpur_Logo.svg.png",
    },
    { id: 3, name: "IIT Bombay", logo: "/imgi_7_IIT-Bombay_Logo.svg.png" },
    // { id: 4, name: "IIT Kanpur", logo: "/imgi_18_IIT_Kanpur_Logo.svg.png" },
    { id: 5, name: "IIT Madras", logo: "/imgi_20_IIT_Madras_Logo.svg.png" },
    { id: 6, name: "IIT Delhi", logo: "/imgi_8_iit-delhi.png" },
    // { id: 7, name: "IIT Guwahati", logo: "/imgi_12_IIT_Guwahati_Logo.svg.png" },
    { id: 8, name: "IIT Roorkee", logo: "/imgi_24_IIT-Roorkee_logo.png" },
    { id: 9, name: "IIT Jodhpur", logo: "/imgi_17_IIT-Jodhpur_Logo.svg.png" },
    { id: 10, name: "IIT Ropar", logo: "/imgi_25_IIT-Ropar_logo .png" },
    {
      id: 11,
      name: "IIT Gandhinagar",
      logo: "/imgi_10_IIT_Gandhinagar_Logo.svg.png",
    },
    {
      id: 12,
      name: "IIT Hyderabad",
      logo: "/imgi_13_IIT_Hyderabad_Insignia.svg.png",
    },
    { id: 13, name: "IIT Patna", logo: "/imgi_23_IIT-Patna.svg.png" },
    {
      id: 14,
      name: "IIT Bhuneshwar",
      logo: "/imgi_6_iitb_bhubaneswar_logo .png",
    },
    { id: 15, name: "IIT Mandi", logo: "/imgi_21_IIT-Mandi_Logo.png" },
    { id: 16, name: "IIT Indore", logo: "/imgi_14_IIT-Indore.png" },
    { id: 17, name: "IIT (BHU) Varanasi", logo: "/bhu.png" },
    {
      id: 18,
      name: "IIT Palakkad",
      logo: "/imgi_22_330px-IIT_Palakkad_Logo.svg.png",
    },
    { id: 19, name: "IIT Tirupati", logo: "/imgi_26_IIT-Tirupati_logo .jpg" },
    { id: 20, name: "IIT(ISM) Dhanbad", logo: "/iitism-logo.png" },
    { id: 21, name: "IIT Bhilai", logo: "/imgi_4_IIT_Bhilai_logo.png" },
    // { id: 22, name: "IIT Dharwad", logo: "/imgi_9_IITDh.png" },
    { id: 23, name: "IIT Jammu", logo: "/imgi_16_IIT-Jammu.png" },
    { id: 24, name: "IIT Goa", logo: "/imgi_11_IIT-Goa_Logo.svg.png" },
  ],

  organizer: [
    {
      id: 1,
      name: "IIT KHARAGPUR",
      logo: "/imgi_19_IIT_Kharagpur_Logo.svg.png",
      link: "https://www.iitkgp.ac.in/",
    },
    {
      id: 2,
      name: "IIT(BHU) VARANASI",
      logo: "/bhu.png",
      link: "https://www.iitbhu.ac.in/",
    },
    {
      id: 3,
      name: "IIT(ISM) DHANBAD",
      logo: "/iitism-logo.png",
      link: "https://www.iitism.ac.in/",
    },
    {
      id: 4,
      name: "IIT PATNA",
      logo: "/imgi_23_IIT-Patna.svg.png",
      link: "https://www.iitp.ac.in/",
    },
    {
      id: 5,
      name: "IIT BHUBANESWAR",
      logo: "/imgi_6_iitb_bhubaneswar_logo .png",
      link: "https://www.iitbbs.ac.in/",
    },
  ],

  nit: [
    {
      id: 32,
      name: "IIEST SHIBPUR",
      logo: "/Indian_Institute_of_Engineering_Science_and_Technology,_Shibpur_Logo.png",
    },
    // {
    //   id: 1,
    //   name: "NIT Agartala",
    //   logo: "/imgi_27_National_Institute_of_Technology,_Agartala_Logo .png",
    // },
    // {
    //   id: 2,
    //   name: "NIT Allahabad",
    //   logo: "/imgi_28_Motilal_Nehru_National_Institute_of_Technology_Allahabad_logo .png",
    // },
    // {
    //   id: 3,
    //   name: "NIT Andhra Pradesh",
    //   logo: "/imgi_29_NIT_Andhra_Pradesh .png",
    // },
    // {
    //   id: 4,
    //   name: "NIT Arunachal Pradesh",
    //   logo: "/imgi_30_National_Institute_of_Technology,_Arunachal_Pradesh_Logo.png",
    // },
    // {
    //   id: 5,
    //   name: "NIT Bhopal",
    //   logo: "/imgi_31_Maulana_Azad_National_Institute_of_Technology_Logo.png",
    // },
    // { id: 6, name: "NIT Delhi", logo: "/imgi_33_NIT-Delhi_Logo.svg.png" },
    { id: 7, name: "NIT Durgapur", logo: "/imgi_34_NIT_Durgapur_Logo.svg.png" },
    // { id: 8, name: "NIT Goa", logo: "/imgi_35_NIT_Goa_logo.png" },
    // {
    //   id: 9,
    //   name: "NIT Hamipur",
    //   logo: "/imgi_36_National_Institute_of_Technology,_Hamirpur_Logo.png",
    // },
    // { id: 10, name: "NIT Jaipur", logo: "/imgi_37_Mnit_logo.png" },
    // {
    //   id: 11,
    //   name: "NIT Jalandhar",
    //   logo: "/imgi_38_Logo_of_NIT_Jalandhar.png",
    // },
    {
      id: 12,
      name: "NIT Jamshedpur",
      logo: "/imgi_39_National_Institute_of_Technology,_Jamshedpur_Logo (1).png",
    },
    {
      id: 13,
      name: "NIT Kalicut",
      logo: "/imgi_32_Correct_Logo_of_NIT_Calicut.svg.png",
    },
    // {
    //   id: 14,
    //   name: "NIT Kurukshretra",
    //   logo: "/imgi_40_National_Institute_of_Technology,_kuru.png",
    // },
    // {
    //   id: 15,
    //   name: "NIT Manipur",
    //   logo: "/imgi_41_National_Institute_of_Technology,_Manipur_logo.png",
    // },
    // {
    //   id: 16,
    //   name: "NIT Meghalaya",
    //   logo: "/imgi_42_National_Institute_of_Technology,_Meghalaya_logo.png",
    // },
    // {
    //   id: 17,
    //   name: "NIT Mizoram",
    //   logo: "/imgi_43_National_Institute_of_Technology_Mizoram_logo.png",
    // },
    // {
    //   id: 18,
    //   name: "NIT Nagaland",
    //   logo: "/imgi_44_National_Institute_of_Technology,_Nagaland_Logo.png",
    // },
    // { id: 19, name: "NIT Nagpur", logo: "/imgi_45_VNIT_logo.jpg" },
    // {
    //   id: 20,
    //   name: "NIT Patna",
    //   logo: "/imgi_46_National_Institute_of_Technology,_Patna_Logo.png",
    // },
    // {
    //   id: 21,
    //   name: "NIT Puducherry",
    //   logo: "/imgi_47_NIT_Puducherry_Official_logo.png",
    // },
    // {
    //   id: 22,
    //   name: "NIT Raipur",
    //   logo: "/imgi_48_National_Institute_of_Technology,_Raipur_Logo.png",
    // },
    {
      id: 23,
      name: "NIT Rourkela",
      logo: "/imgi_49_NIT_Rourkela_Colour_Logo.svg.png",
    },
    // {
    //   id: 24,
    //   name: "NIT Sikkim",
    //   logo: "/imgi_50_National_Institute_of_Technology_Sikkim.svg.png",
    // },
    {
      id: 25,
      name: "NIT Silchar",
      logo: "/imgi_51_National_Institute_Of_Technology_Silchar_Logo.svg.png",
    },
    // {
    //   id: 26,
    //   name: "NIT Srinagar",
    //   logo: "/imgi_52_National_Institute_of_Technology,_Srinagar_Logo.png",
    // },
    // { id: 27, name: "NIT Surat", logo: "/imgi_53_NIT_Surat_Logo.svg.png" },
    { id: 28, name: "NIT Surathakal", logo: "/NITK-Surathkal-logo.png" },
    {
      id: 29,
      name: "NIT Tiruchirappalli",
      logo: "/imgi_54_National_Institute_of_Technology_Trichy_Logo.png",
    },
    // {
    //   id: 30,
    //   name: "NIT Uttrakhand",
    //   logo: "/imgi_55_NIT_Uttarakhand_Logo.png",
    // },
    {
      id: 31,
      name: "NIT Warangal",
      logo: "/imgi_56_National_Institute_of_Technology,_Warangal_logo.png",
    },
     {
      id: 56,
      name: "VNIT Nagpur",
      logo: "/VNIT nagpur.jpeg",
    },
     {
      id: 57,
      name: "MNIT Jaipur",
      logo: "/mnit jaipur.png",
    },
  ],

  iiser: [
    { id: 1, name: "IISER Kolkata", logo: "/imgi_58_IISER-K_Logo.svg.png" },
    // { id: 2, name: "IISER PUNE", logo: "/imgi_57_IISER,_PUNE_Logo.svg.png" },
    // { id: 3, name: "IISER Mohali", logo: "/imgi_59_IISER-Mohali_Logo.svg.png" },
    // { id: 4, name: "IISER Bhopal", logo: "/imgi_62_IISERB_logo (1).png" },
    // {
    //   id: 5,
    //   name: "IISER Tiruvanathapuram",
    //   logo: "/imgi_60_IISER_Thiruvananthapuram_Logo.svg.png",
    // },
    // {
    //   id: 6,
    //   name: "IISER Tirupati",
    //   logo: "/imgi_61_IISER_Tirupati_logo (1).png",
    // },
    // {
    //   id: 7,
    //   name: "IISER Berhampur",
    //   logo: "/imgi_63_Indian_Institute_of_Science_Education_and_Research_Berhampur_Logo.svg.png",
    // },
  ],
  iims:[],

  top: [
    // {
    //   id: 1,
    //   name: "Birla Institute of Technology & Science -Pilani, Rajasthan",
    //   logo: "/bit_pilani.png",
    // },
    {
      id: 2,
      name: "S.R.M. Institute of Science and Technology, Tamil Nadu",
      logo: "/CLG_66eff16d46661.png",
    },
    // {
    //   id: 3,
    //   name: "Vellore Institute of Technology, Tamil Nadu",
    //   logo: "/Vellore_Institute_of_Technology_seal_2017.svg.png",
    // },
    // {
    //   id: 4,
    //   name: "Jadavpur University, West Bengal",
    //   logo: "/Jadavpur_University_Logo.svg.png",
    // },
    // {
    //   id: 5,
    //   name: "Anna University, Tamil Nadu",
    //   logo: "/anna_university.png",
    // },
    // { id: 6, name: "Siksha O Anusandhan, Odisha", logo: "/SOA-PNG.webp" },
    // {
    //   id: 7,
    //   name: "Amrita Vishwa Vidyapeetham, Tamil Nadu",
    //   logo: "/amrita_vishwa.png",
    // },
    // {
    //   id: 8,
    //   name: "Jamia Millia Islamia, Delhi",
    //   logo: "/Jamia_Millia_Islamia_Logo.svg",
    // },
    // {
    //   id: 9,
    //   name: "Thapar Institute of Engineering and Technology, Punjab",
    //   logo: "/TIET - Thapar Institute of Engineering And Technology_logo210626104431.png",
    // },
    {
      id: 10,
      name: "Delhi Technological University, Delhi",
      logo: "/DTU,_Delhi_official_logo.png",
    },
    // {
    //   id: 11,
    //   name: "Chandigarh University, Punjab",
    //   logo: "/Chandigarh_University_Seal.png",
    // },
    // {
    //   id: 12,
    //   name: "Kalasalingam Academy of Research and Education, Tamil Nadu",
    //   logo: "/Kalasalingam_Academy_of_Research_and_Education_logo.png",
    // },
    // {
    //   id: 13,
    //   name: "Aligarh Muslim University, Uttar Pradesh",
    //   logo: "/aligarh.png",
    // },
    // {
    //   id: 14,
    //   name: "K L College of Engineering, Andhra Pradesh",
    //   logo: "/b0nlyalv.uyd.jpg",
    // },
    // {
    //   id: 15,
    //   name: "Kalinga Institute of Industrial Technology, Odisha",
    //   logo: "/KIIT_logo.svg.png",
    // },
    // {
    //   id: 16,
    //   name: "Amity University, Uttar Pradesh",
    //   logo: "/amity_university.png",
    // },
    // {
    //   id: 17,
    //   name: "IIIT Hyderabad, Telangana",
    //   logo: "/IIIT_Hyderabad_Logo-e1655116937986.jpg",
    // },
    // {
    //   id: 18,
    //   name: "Shanmugha Arts Science Technology & Research Academy, Tamil Nadu",
    //   logo: "/Shanmugha_Arts,_Science,_Technology_&_Research_Academy.svg.png",
    // },
    // {
    //   id: 19,
    //   name: "Institute of Chemical Technology, Maharashtra",
    //   logo: "/Institute_of_Chemical_Technology_logo.png",
    // },
    // { id: 20, name: "UPES Dehradun, Uttarakhand", logo: "upes.jpg" },
    // {
    //   id: 21,
    //   name: "Saveetha Institute of Medical and Technical Sciences, Tamil Nadu",
    //   logo: "/saveetha.png",
    // },
    // {
    //   id: 22,
    //   name: "Symbiosis International, Maharashtra",
    //   logo: "/Logo_of_Symbiosis_International_University.svg.png",
    // },
    // {
    //   id: 23,
    //   name: "Sri Sivasubramaniya Nadar College of Engineering, Tamil Nadu",
    //   logo: "/ssn.png",
    // },
    // {
    //   id: 24,
    //   name: "Lovely Professional University, Punjab",
    //   logo: "/Lovely_Professional_University_04_37bc70298e.png",
    // },
    // { id: 25, name: "BIT Mesra, Jharkhand", logo: "/bit_mesra.png" },
    // {
    //   id: 26,
    //   name: "Graphic Era University, Uttarakhand",
    //   logo: "/geu-small-logo.png",
    // },
    // {
    //   id: 27,
    //   name: "Manipal University Jaipur, Rajasthan",
    //   logo: "/manipal_institue.png",
    // },
    // {
    //   id: 28,
    //   name: "Manipal Institute of Technology, Karnataka",
    //   logo: "/manipal_institue.png",
    // },
    // {
    //   id: 29,
    //   name: "Madan Mohan Malaviya University of Technology, Uttar Pradesh",
    //   logo: "/madan_mohan.png",
    // },
    // {
    //   id: 30,
    //   name: "Indian Institute of Space Science and Technology, Kerala",
    //   logo: "/Indian_Institute_of_Space_Science_and_Technology_Logo.png",
    // },
    // {
    //   id: 31,
    //   name: "Indraprastha Institute of Information Technology, Delhi",
    //   logo: "/iiid.jpg",
    // },
    // {
    //   id: 32,
    //   name: "PSG College of Technology, Tamil Nadu",
    //   logo: "/PSGCT-Coimbatore-Logo.webp",
    // },
    // {
    //   id: 33,
    //   name: "Sathyabama Institute of Science and Technology, Tamil Nadu",
    //   logo: "/Sathyabama_Institute_of_Science_and_Technology_logo (1).png",
    // },
    // { id: 34, name: "IIIT Bangalore, Karnataka", logo: "IIITB_logo1.png" },
    // {
    //   id: 35,
    //   name: "Netaji Subhas University of Technology, Delhi",
    //   logo: "/Netaji_Subhas_University_of_Technology.svg",
    // },
    // {
    //   id: 36,
    //   name: "Banasthali Vidyapith, Rajasthan",
    //   logo: "/banasthali.png",
    // },
    // {
    //   id: 37,
    //   name: "University of Hyderabad, Telangana",
    //   logo: "/University_of_Hyderabad_Logo.png",
    // },
    // {
    //   id: 38,
    //   name: "M. S. Ramaiah Institute of Technology, Karnataka",
    //   logo: "/Ramaiah_Institutions_Logo.png",
    // },
    // { id: 39, name: "Christ University, Karnataka", logo: "/crist.avif" },
    // {
    //   id: 40,
    //   name: "Rajiv Gandhi Institute of Petroleum Technology, Uttar Pradesh",
    //   logo: "/Rajiv_Gandhi_Institute_of_Petroleum_Technology.png",
    // },
    // {
    //   id: 41,
    //   name: "Sant Longowal Institute of Engineering & Technology, Punjab",
    //   logo: "/sant longowal.jpg",
    // },
    // {
    //   id: 42,
    //   name: "Vignan's Foundation for Science, Technology and Research, Andhra Pradesh",
    //   logo: "/vigans.png",
    // },
    // { id: 43, name: "Jain University, Karnataka", logo: "/jain.png" },
    // {
    //   id: 44,
    //   name: "Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology, Tamil Nadu",
    //   logo: "/Veltech_Rangarajan_Dr._Sagunthala_R&D_Institute_of_Science_and_Technology_logo.png",
    // },
    // {
    //   id: 45,
    //   name: "AU College of Engineering, Andhra Pradesh",
    //   logo: "au_college.png",
    // },
    // { id: 46, name: "Chitkara University, Punjab", logo: "/chitkara.png" },
    // {
    //   id: 47,
    //   name: "COEP Technological University, Maharashtra",
    //   logo: "/coep.jpg",
    // },
    // {
    //   id: 48,
    //   name: "SR University, Telangana",
    //   logo: "SRU_Main_Logo_Colour.png",
    // },
    // {
    //   id: 49,
    //   name: "Defence Institute of Advanced Technology, Maharashtra",
    //   logo: "/Defence_Institute_of_Advanced_Technology.png",
    // },
    // { id: 50, name: "Panjab University, Chandigarh", logo: "/pu-logo.png" },
    // {
    //   id: 51,
    //   name: "Jawaharlal Nehru Technological University, Telangana",
    //   logo: "/JNTU_Hyderabad_logo.png",
    // },
    // {
    //   id: 52,
    //   name: "C.V. Raman Global University, Odisha",
    //   logo: "/C._V._Raman_Global_University_Logo.png",
    // },
    // {
    //   id: 53,
    //   name: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Madhya Pradesh",
    //   logo: "/atal_bihari.jpg",
    // },
    // {
    //   id: 54,
    //   name: "Pandit Deendayal Energy University, Gujarat",
    //   logo: "/Pandit_Deendayal_Energy_University_logo.png",
    // },
    // {
    //   id: 55,
    //   name: "Sri Krishna College of Engineering and Technology, Tamil Nadu",
    //   logo: "/sri_krishna_college_of_engineering_and_technology_official_logo.jpg",
    // },
    // {
    //   id: 56,
    //   name: "VNIT Nagpur",
    //   logo: "/VNIT nagpur.jpeg",
    // },
    //  {
    //   id: 57,
    //   name: "MNIT Jaipur",
    //   logo: "/mnit jaipur.png",
    // },
    //  {
    //   id: 58,
    //   name: "NITTTR Bhopal",
    //   logo: "/nitttr bhopal.jpg",
    // },
  ],
  theme: [
    {
      id: 1,
      name: "IIT KHARAGPUR",
      themes: "Health Care",
      logo: "/health.jpeg",
      link: "https://www.iitkgp.ac.in/",
    },
    {
      id: 2,
      name: "IIT(BHU) VARANASI",
      themes: "Materials Science",
      logo: "/material.jpeg",
      link: "https://www.iitbhu.ac.in/",
    },
    {
      id: 3,
      name: "IIT(ISM) DHANBAD",
      themes: "Earth Sciences",
      logo: "/earth.jpeg",
      link: "https://www.iitism.ac.in/",
    },
    {
      id: 4,
      name: "IIT PATNA",
      themes: "Artificial Intelligence",
      logo: "/artificial.jpeg",
      link: "https://www.iitp.ac.in/",
    },
    {
      id: 5,
      name: "IIT BHUBANESWAR",
      themes: "Semiconductor Technology & Chip Design",
      logo: "/semiconductor.jpeg",
      link: "https://www.iitbbs.ac.in/",
    },
  ],

  tableData: [
    {
      sl: 1,
      institute: "IIT Madras",
      aiml: 2,
      semiconductor: "-",
      earthScience: 1,
      materialsScience: 5,
      healthCare: 6,
      total: 14,
    },
    {
      sl: 2,
      institute: "IIT Delhi",
      aiml: 1,
      semiconductor: "-",
      earthScience: "-",
      materialsScience: "-",
      healthCare: 1,
      total: 2,
    },
    {
      sl: 3,
      institute: "IIT Gandhinagar",
      aiml: 1,
      semiconductor: 1,
      earthScience: "-",
      materialsScience: 2,
      healthCare: 2,
      total: 6,
    },
    {
      sl: 4,
      institute: "IIT Mandi",
      aiml: "-",
      semiconductor: 1,
      earthScience: 1,
      materialsScience: "-",
      healthCare: 2,
      total: 4,
    },
    {
      sl: 5,
      institute: "IIT Bhubneswar",
      aiml: 2,
      semiconductor: 2,
      earthScience: "-",
      materialsScience: 2,
      healthCare: 2,
      total: 8,
    },
    {
      sl: 6,
      institute: "IIT Tirupati",
      aiml: 1,
      semiconductor: "-",
      earthScience: 1,
      materialsScience: 2,
      healthCare: 2,
      total: 6,
    },
    {
      sl: 7,
      institute: "IIT Palakkad",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: 1,
      healthCare: 1,
      total: 2,
    },
    {
      sl: 8,
      institute: "IIT Bhilai",
      aiml: 1,
      semiconductor: 2,
      earthScience: "-",
      materialsScience: 2,
      healthCare: 1,
      total: 6,
    },
    {
      sl: 9,
      institute: "IIT Patna",
      aiml: 4,
      semiconductor: "-",
      earthScience: "-",
      materialsScience: "-",
      healthCare: "-",
      total: 4,
    },
    {
      sl: 10,
      institute: "IIT(ISM) Dhanbad",
      aiml: 2,
      semiconductor: "-",
      earthScience: 7,
      materialsScience: 1,
      healthCare: "-",
      total: 10,
    },
    {
      sl: 11,
      institute: "IIT Roorkee",
      aiml: 1,
      semiconductor: "-",
      earthScience: 2,
      materialsScience: "-",
      healthCare: 2,
      total: 5,
    },
    {
      sl: 12,
      institute: "IIT Goa",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: "-",
      healthCare: 1,
      total: 1,
    },
    {
      sl: 13,
      institute: "IIEST Shibpur",
      aiml: 2,
      semiconductor: "_",
      earthScience: "-",
      materialsScience: "-",
      healthCare: 5,
      total: 7,
    },
    {
      sl: 14,
      institute: "IISER Pune",
      aiml: "-",
      semiconductor: "_",
      earthScience: "-",
      materialsScience: "-",
      healthCare: 1,
      total: 1,
    },
    {
      sl: 15,
      institute: "NIT Silchar",
      aiml: 7,
      semiconductor: "_",
      earthScience: 2,
      materialsScience: 7,
      healthCare: 1,
      total: 17,
    },

    {
      sl: 16,
      institute: "SRM",
      aiml: 2,
      semiconductor: 2,
      earthScience: "-",
      materialsScience: 1,
      healthCare: 2,
      total: 7,
    },
    {
      sl: 17,
      institute: "NIT Durgapur",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: "-",
      healthCare: 1,
      total: 1,
    },
    {
      sl: 18,
      institute: "VIT Vellore",
      aiml: 2,
      semiconductor: 2,
      earthScience: "-",
      materialsScience: "-",
      healthCare: 18,
      total: 22,
    },
    {
      sl: 19,
      institute: "IIT BHU",
      aiml: 1,
      semiconductor: 1,
      earthScience: "-",
      materialsScience: "-",
      healthCare: 8,
      total: 10,
    },
    {
      sl: 20,
      institute: "IIT Bombay",
      aiml: 1,
      semiconductor: 1,
      earthScience: "-",
      materialsScience: 3,
      healthCare: 5,
      total: 10,
    },
    {
      sl: 21,
      institute: "IIT Jammu",
      aiml: 2,
      semiconductor: "-",
      earthScience: 1,
      materialsScience: 1,
      healthCare: "-",
      total: 4,
    },
    {
      sl: 22,
      institute: "DTU Delhi",
      aiml: 2,
      semiconductor: "-",
      earthScience: "-",
      materialsScience: "-",
      healthCare: "-",
      total: 2,
    },
    {
      sl: 23,
      institute: "NIT Warangal",
      aiml: "-",
      semiconductor: 1,
      earthScience: "-",
      materialsScience: 3,
      healthCare: 1,
      total: 5,
    },
    {
      sl: 24,
      institute: "NIT Surathkal",
      aiml: "-",
      semiconductor: "-",
      earthScience: 1,
      materialsScience: "-",
      healthCare: 1,
      total: 2,
    },
    {
      sl: 25,
      institute: "NIT Jamshedpur",
      aiml: 3,
      semiconductor: 1,
      earthScience: "-",
      materialsScience: 1,
      healthCare: 2,
      total: 7,
    },
    {
      sl: 26,
      institute: "IISER Kolkata",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: "-",
      healthCare: 1,
      total: 1,
    },
    {
      sl: 27,
      institute: "IIT Hyderabad",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: 2,
      healthCare: 4,
      total: 6,
    },
    {
      sl: 28,
      institute: "IIT Indore",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: 4,
      healthCare: 3,
      total: 7,
    },
    {
      sl: 29,
      institute: "NITTTR Bhopal",
      aiml: "-",
      semiconductor: 3,
      earthScience: "-",
      materialsScience: "-",
      healthCare: "-",
      total: 3,
    },
    {
      sl: 30,
      institute: "IIT Kharagpur",
      aiml: 2,
      semiconductor: "-",
      earthScience: 2,
      materialsScience: "-",
      healthCare: 4,
      total: 8,
    },
    {
      sl: 31,
      institute: "IIT Jodhpur",
      aiml: 1,
      semiconductor: "-",
      earthScience: "-",
      materialsScience: 1,
      healthCare: 7,
      total: 9,
    },
    {
      sl: 32,
      institute: "NIT Rourkela",
      aiml: 2,
      semiconductor: "-",
      earthScience: "-",
      materialsScience: 1,
      healthCare: "-",
      total: 3,
    },
    {
      sl: 33,
      institute: "IIT Ropar",
      aiml: 4,
      semiconductor: 3,
      earthScience: 1,
      materialsScience: 3,
      healthCare: 2,
      total: 13,
    },
    {
      sl: 34,
      institute: "MNIT Jaipur",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: 1,
      healthCare: "-",
      total: 1,
    },
    {
      sl: 35,
      institute: "NIT Tiruchirappali",
      aiml: "-",
      semiconductor: "-",
      earthScience: "-",
      materialsScience: 2,
      healthCare: "-",
      total: 2,
    },

    // ✅ Missing 4 rows added here
    {
      sl: 36,
      institute: "NIT Calicut",
      aiml: 1,
      semiconductor: 1,
      earthScience: 1,
      materialsScience: 1,
      healthCare: "-",
      total: 4,
    },
    {
      sl: 37,
      institute: "VNIT Nagpur",
      aiml: "-",
      semiconductor: "-",
      earthScience: 7,
      materialsScience: 1,
      healthCare: "-",
      total: 8,
    },
  ],
  institutesData: [
    {
      sl: 1,
      institute: "IIT (ISM) DHANBAD",
      innovations: [
        { name: "Innovation 1", link: "https://youtube.com/link1" },
        { name: "Innovation 2", link: "https://youtube.com/link2" },
        { name: "Innovation 3", link: "https://youtube.com/link3" },
      ],
    },
    {
      sl: 2,
      institute: "IIT KHARAGPUR",
      innovations: [
        { name: "Innovation A", link: "https://youtube.com/a" },
        { name: "Innovation B", link: "https://youtube.com/b" },
      ],
    },
    {
      sl: 3,
      institute: "IIT(BHU) VARANASI",
      innovations: [
        { name: "Innovation A", link: "https://youtube.com/a" },
        { name: "Innovation B", link: "https://youtube.com/b" },
      ],
    },
    {
      sl: 4,
      institute: "IIT PATNA",
      innovations: [
        { name: "Innovation A", link: "https://youtube.com/a" },
        { name: "Innovation B", link: "https://youtube.com/b" },
      ],
    },
    {
      sl: 5,
      institute: "IIT BHUBANESWAR",
      innovations: [
        { name: "Innovation A", link: "https://youtube.com/a" },
        { name: "Innovation B", link: "https://youtube.com/b" },
      ],
    },
  ],
};
