export const logos = {
  iit: [
    { id: 1, name: "IISc Bangalore", logo: "/IISc_Master_Seal.png" },
    { id: 2, name: "IIT Kharagpur", logo: "/imgi_19_IIT_Kharagpur_Logo.svg.png" },
    { id: 3, name: "IIT Bombay", logo: "/imgi_7_IIT-Bombay_Logo.svg.png" },
    { id: 4, name: "IIT Kanpur", logo: "/imgi_18_IIT_Kanpur_Logo.svg.png" },
    { id: 5, name: "IIT Madras", logo: "/imgi_20_IIT_Madras_Logo.svg.png" },
    { id: 6, name: "IIT Delhi", logo: "/imgi_8_iit-delhi.png" },
    { id: 7, name: "IIT Guwahati", logo: "/imgi_12_IIT_Guwahati_Logo.svg.png" },
    { id: 8, name: "IIT Roorkee", logo: "/imgi_24_IIT-Roorkee_logo.png" },
    { id: 9, name: "IIT Jodhpur", logo: "/imgi_17_IIT-Jodhpur_Logo.svg.png" },
    { id: 10, name: "IIT Ropar", logo: "/imgi_25_IIT-Ropar_logo .png" },
    { id: 11, name: "IIT Gandhinagar", logo: "/imgi_10_IIT_Gandhinagar_Logo.svg.png" },
    { id: 12, name: "IIT Hyderabad", logo: "/imgi_13_IIT_Hyderabad_Insignia.svg.png" },
    { id: 13, name: "IIT Patna", logo: "/imgi_23_IIT-Patna.svg.png" },
    { id: 14, name: "IIT Bhuneshwar", logo: "/imgi_6_iitb_bhubaneswar_logo .png" },
    { id: 15, name: "IIT Mandi", logo: "/imgi_21_IIT-Mandi_Logo.png" },
    { id: 16, name: "IIT Indore", logo: "/imgi_14_IIT-Indore.png" },
    { id: 17, name: "IIT (BHU) Varanasi", logo: "/bhu.png" },
    { id: 18, name: "IIT Palakkad", logo: "/imgi_22_330px-IIT_Palakkad_Logo.svg.png" },
    { id: 19, name: "IIT Tirupati", logo: "/imgi_26_IIT-Tirupati_logo .jpg" },
    { id: 20, name: "IIT(ISM) Dhanbad", logo: "/iitism-logo.png" },
    { id: 21, name: "IIT Bhilai", logo: "/imgi_4_IIT_Bhilai_logo.png" },
    { id: 22, name: "IIT Dharwad", logo: "/imgi_9_IITDh.png" },
    { id: 23, name: "IIT Jammu", logo: "/imgi_16_IIT-Jammu.png" },
    { id: 24, name: "IIT Goa", logo: "/imgi_11_IIT-Goa_Logo.svg.png" },
  ],

  organizer: [
    { id: 1, name: "IIT KHARAGPUR", logo: "/imgi_19_IIT_Kharagpur_Logo.svg.png" },
    { id: 2, name: "IIT(BHU) VARANASI", logo: "/bhu.png" },
    { id: 3, name: "IIT(ISM) DHANBAD", logo: "/iitism-logo.png" },
    { id: 4, name: "IIT PATNA", logo: "/imgi_23_IIT-Patna.svg.png" },
    { id: 5, name: "IIT BHUBANESWAR", logo: "/imgi_6_iitb_bhubaneswar_logo .png" },
  ],


  nit: [
    { id: 32, name: "IIEST SHIBPUR", logo: "/Indian_Institute_of_Engineering_Science_and_Technology,_Shibpur_Logo.png" },
    { id: 1, name: "NIT Agartala", logo: "/imgi_27_National_Institute_of_Technology,_Agartala_Logo .png" },
    { id: 2, name: "NIT Allahabad", logo: "/imgi_28_Motilal_Nehru_National_Institute_of_Technology_Allahabad_logo .png" },
    { id: 3, name: "NIT Andhra Pradesh", logo: "/imgi_29_NIT_Andhra_Pradesh .png" },
    { id: 4, name: "NIT Arunachal Pradesh", logo: "/imgi_30_National_Institute_of_Technology,_Arunachal_Pradesh_Logo.png" },
    { id: 5, name: "NIT Bhopal", logo: "/imgi_31_Maulana_Azad_National_Institute_of_Technology_Logo.png" },
    { id: 6, name: "NIT Delhi", logo: "/imgi_33_NIT-Delhi_Logo.svg.png" },
    { id: 7, name: "NIT Durgapur", logo: "/imgi_34_NIT_Durgapur_Logo.svg.png" },
    { id: 8, name: "NIT Goa", logo: "/imgi_35_NIT_Goa_logo.png" },
    { id: 9, name: "NIT Hamipur", logo: "/imgi_36_National_Institute_of_Technology,_Hamirpur_Logo.png" },
    { id: 10, name: "NIT Jaipur", logo: "/imgi_37_Mnit_logo.png" },
    { id: 11, name: "NIT Jalandhar", logo: "/imgi_38_Logo_of_NIT_Jalandhar.png" },
    { id: 12, name: "NIT Jamshedpur", logo: "/imgi_39_National_Institute_of_Technology,_Jamshedpur_Logo (1).png" },
    { id: 13, name: "NIT Kalicut", logo: "/imgi_32_Correct_Logo_of_NIT_Calicut.svg.png" },
    { id: 14, name: "NIT Kurukshretra", logo: "/imgi_40_National_Institute_of_Technology,_kuru.png" },
    { id: 15, name: "NIT Manipur", logo: "/imgi_41_National_Institute_of_Technology,_Manipur_logo.png" },
    { id: 16, name: "NIT Meghalaya", logo: "/imgi_42_National_Institute_of_Technology,_Meghalaya_logo.png" },
    { id: 17, name: "NIT Mizoram", logo: "/imgi_43_National_Institute_of_Technology_Mizoram_logo.png" },
    { id: 18, name: "NIT Nagaland", logo: "/imgi_44_National_Institute_of_Technology,_Nagaland_Logo.png" },
    { id: 19, name: "NIT Nagpur", logo: "/imgi_45_VNIT_logo.jpg" },
    { id: 20, name: "NIT Patna", logo: "/imgi_46_National_Institute_of_Technology,_Patna_Logo.png" },
    { id: 21, name: "NIT Puducherry", logo: "/imgi_47_NIT_Puducherry_Official_logo.png" },
    { id: 22, name: "NIT Raipur", logo: "/imgi_48_National_Institute_of_Technology,_Raipur_Logo.png" },
    { id: 23, name: "NIT Rourkela", logo: "/imgi_49_NIT_Rourkela_Colour_Logo.svg.png" },
    { id: 24, name: "NIT Sikkim", logo: "/imgi_50_National_Institute_of_Technology_Sikkim.svg.png" },
    { id: 25, name: "NIT Silchar", logo: "/imgi_51_National_Institute_Of_Technology_Silchar_Logo.svg.png" },
    { id: 26, name: "NIT Srinagar", logo: "/imgi_52_National_Institute_of_Technology,_Srinagar_Logo.png" },
    { id: 27, name: "NIT Surat", logo: "/imgi_53_NIT_Surat_Logo.svg.png" },
    { id: 28, name: "NIT Surathakal", logo: "/NITK-Surathkal-logo.png" },
    { id: 29, name: "NIT Tiruchirappalli", logo: "/imgi_54_National_Institute_of_Technology_Trichy_Logo.png" },
    { id: 30, name: "NIT Uttrakhand", logo: "/imgi_55_NIT_Uttarakhand_Logo.png" },
    { id: 31, name: "NIT Warangal", logo: "/imgi_56_National_Institute_of_Technology,_Warangal_logo.png" },
  ],

  iiser: [
    { id: 1, name: "IISER Kolkata", logo: "/imgi_58_IISER-K_Logo.svg.png" },
    { id: 2, name: "IISER PUNE", logo: "/imgi_57_IISER,_PUNE_Logo.svg.png" },
    { id: 3, name: "IISER Mohali", logo: "/imgi_59_IISER-Mohali_Logo.svg.png" },
    { id: 4, name: "IISER Bhopal", logo: "/imgi_62_IISERB_logo (1).png" },
    { id: 5, name: "IISER Tiruvanathapuram", logo: "/imgi_60_IISER_Thiruvananthapuram_Logo.svg.png" },
    { id: 6, name: "IISER Tirupati", logo: "/imgi_61_IISER_Tirupati_logo (1).png" },
    { id: 7, name: "IISER Berhampur", logo: "/imgi_63_Indian_Institute_of_Science_Education_and_Research_Berhampur_Logo.svg.png" },

  ],
  top: [
    { id: 1, name: "Birla Institute of Technology & Science -Pilani, Rajasthan" },
    { id: 2, name: "S.R.M. Institute of Science and Technology, Tamil Nadu" },
    { id: 3, name: "Vellore Institute of Technology, Tamil Nadu" },
    { id: 4, name: "Jadavpur University, West Bengal" },
    { id: 5, name: "Anna University, Tamil Nadu" },
    { id: 6, name: "Siksha O Anusandhan, Odisha" },
    { id: 7, name: "Amrita Vishwa Vidyapeetham, Tamil Nadu" },
    { id: 8, name: "Jamia Millia Islamia, Delhi" },
    { id: 9, name: "Thapar Institute of Engineering and Technology, Punjab" },
    { id: 10, name: "Delhi Technological University, Delhi" },
    { id: 11, name: "Chandigarh University, Punjab" },
    { id: 12, name: "Kalasalingam Academy of Research and Education, Tamil Nadu" },
    { id: 13, name: "Aligarh Muslim University, Uttar Pradesh" },
    { id: 14, name: "K L College of Engineering, Andhra Pradesh" },
    { id: 15, name: "Kalinga Institute of Industrial Technology, Odisha" },
    { id: 16, name: "Amity University, Uttar Pradesh" },
    { id: 17, name: "IIIT Hyderabad, Telangana" },
    { id: 18, name: "Shanmugha Arts Science Technology & Research Academy, Tamil Nadu" },
    { id: 19, name: "Institute of Chemical Technology, Maharashtra" },
    { id: 20, name: "UPES Dehradun, Uttarakhand" },
    { id: 21, name: "Saveetha Institute of Medical and Technical Sciences, Tamil Nadu" },
    { id: 22, name: "Symbiosis International, Maharashtra" },
    { id: 23, name: "Sri Sivasubramaniya Nadar College of Engineering, Tamil Nadu" },
    { id: 24, name: "Lovely Professional University, Punjab" },
    { id: 25, name: "BIT Mesra, Jharkhand" },
    { id: 26, name: "Graphic Era University, Uttarakhand" },
    { id: 27, name: "Manipal University Jaipur, Rajasthan" },
    { id: 28, name: "Manipal Institute of Technology, Karnataka" },
    { id: 29, name: "Madan Mohan Malaviya University of Technology, Uttar Pradesh" },
    { id: 30, name: "Indian Institute of Space Science and Technology, Kerala" },
    { id: 31, name: "Indraprastha Institute of Information Technology, Delhi" },
    { id: 32, name: "PSG College of Technology, Tamil Nadu" },
    { id: 33, name: "Sathyabama Institute of Science and Technology, Tamil Nadu" },
    { id: 34, name: "IIIT Bangalore, Karnataka" },
    { id: 35, name: "Netaji Subhas University of Technology, Delhi" },
    { id: 36, name: "Banasthali Vidyapith, Rajasthan" },
    { id: 37, name: "University of Hyderabad, Telangana" },
    { id: 38, name: "M. S. Ramaiah Institute of Technology, Karnataka" },
    { id: 39, name: "Christ University, Karnataka" },
    { id: 40, name: "Rajiv Gandhi Institute of Petroleum Technology, Uttar Pradesh" },
    { id: 41, name: "Sant Longowal Institute of Engineering & Technology, Punjab" },
    { id: 42, name: "Vignan's Foundation for Science, Technology and Research, Andhra Pradesh" },
    { id: 43, name: "Vignan's Foundation for Science, Technology and Research, Andhra Pradesh" },
    { id: 44, name: "Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology, Tamil Nadu" },
    { id: 45, name: "AU College of Engineering, Andhra Pradesh" },
    { id: 46, name: "Chitkara University, Punjab" },
    { id: 47, name: "COEP Technological University, Maharashtra" },
    { id: 48, name: "SR University, Telangana" },
    { id: 49, name: "Defence Institute of Advanced Technology, Maharashtra" },
    { id: 50, name: "Panjab University, Chandigarh" },
    { id: 51, name: "Jawaharlal Nehru Technological University, Telangana" },
    { id: 52, name: "C.V. Raman Global University, Odisha" },
    { id: 53, name: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Madhya Pradesh" },
    { id: 54, name: "Pandit Deendayal Energy University, Gujarat" },
    { id: 55, name: "Sri Krishna College of Engineering and Technology, Tamil Nadu" },
  ],
  theme: [
    { id: 1, name: "IIT KHARAGPUR", themes: "Health Care", logo: "/health.jpeg", link: "/hosts/kharagpur/1" },
    { id: 2, name: "IIT(BHU) VARANASI", themes: "Materials Science", logo: "/material.jpeg", link: "/hosts/varanasi/2" },
    { id: 3, name: "IIT(ISM) DHANBAD", themes: "Earth Sciences", logo: "/earth.jpeg", link: "/hosts/dhanbad/3" },
    { id: 4, name: "IIT PATNA", themes: "Artificial Intelligence", logo: "/artificial.jpeg", link: "/hosts/patna/4" },
    { id: 5, name: "IIT BHUBANESWAR", themes: "Semiconductor Technology & Chip Design", logo: "/semiconductor.jpeg", link: "/hosts/bhubaneswar/5" },


  ]
}